### PR TITLE
Allow open ended ranges like 1980-Present

### PR DESCRIPTION
**Pull request by blevine-reverb**

### CODE REVIEW

**Review by mcostanza — COMMENTED** [review]
Code change looks good. We'll also need to publish a new version of this gem, I'm not sure what we used to do, but based on past PRs it involved manual version bumps. We should probably use a similar script to what we use for other internal gems? Also this is a public repository, should it be private?

**Comment by wenn** [comment]
> We'll also need to publish a new version of this gem, I'm not sure what we used to do, but based on past PRs it involved manual version bumps.

Hopefully the readme is not outdated, https://github.com/reverbdotcom/flexyear#publish-a-new-version.

**Review by wenn — APPROVED** [review]
pre-approving, but needs a version bump.

**Review by mcostanza — APPROVED** [review]

**Comment by danmelnick** [comment]
👍 nice work friends

**Comment by blevine-reverb** [comment]
> 👍 nice work friends

🙇 We don't see much code with your name on it anymore! It's a welcome surprise.

**Pull request merged**
